first_app/urls.py
from django.urls import path

from . import views
from first_app import views

# TEMPLATE TAGGING
app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('formpage/', views.form_name_view, name='form_name'),
    path('adminsignup/', views.signup_name_view, name='signup_name'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('login/', views.user_login, name='user_login'),
    path('special/', views.special, name='special'),
    

]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

first_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey('Topic', on_delete = models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccesRecord(models.Model):
    name = models.ForeignKey('Webpage', on_delete = models.CASCADE)
    date = models.DateField(unique=True)

    def __str__(self):
        return self.date

# For admin sign up
class NewAdmin(models.Model):
    name = models.CharField(max_length=264, unique=True)
    email = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.name

# For user registration
class UserProfileInfor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user

first_app/forms.py
from dataclasses import field, fields
import email
from itertools import tee
from django import forms
from django.core.exceptions import ValidationError

from .models import User
from first_app.models import UserProfileInfor

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label= 'Enter Your Email Again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data.get('verify_email')

        if email != vmail:
            raise forms.ValidationError("Make Sure Emails Match")

# this is for admin
class NewUserForm(forms.ModelForm):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label= 'Enter Your Email Again')

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data.get('verify_email')

        if email != vmail:
            raise forms.ValidationError("Make Sure Emails Match")

    class Meta():
        model = User
        fields = ['name', 'email']

# this is for user
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfor
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from cmath import log
from os import access
import profile
from django.shortcuts import render, redirect
from first_app.models import Topic, Webpage, AccesRecord
from . import forms
from django.forms import ModelForm
from first_app.forms import UserForm, UserProfileInfoForm

#login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    webpage_list = AccesRecord.objects.order_by('date')
    date_dict = {'access_records' : webpage_list}   
    return render(request, 'first_app/index.html', context=date_dict)

#log in
@login_required
def special(request):
    return render(request, 'first_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request, 'first_app/index.html')


def form_name_view(request):
    form = forms.FormName()

    if request.method =='POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            # DO SOMETHHING CODE
            print("VALIDATION SUCCESS!")
            print("NAME : " + form.cleaned_data['name'])
            print("EMAIL : " + form.cleaned_data['email'])
            print("TEXT : " + form.cleaned_data['text'])


    return render(request, 'first_app/form_page.html', {'form' : form})

    
def signup_name_view(request):
    form = forms.NewUserForm()

    if request.method =='POST':
        form = forms.NewUserForm(request.POST)

        if form.is_valid():
            # DO SOMETHHING CODE
            form.save(commit=True)
            return index(request)
        else:
            print('Error')

    return render(request, 'first_app/signup_page.html', {'form' : form})

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'first_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return render(request, 'first_app/index.html', {})
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        
        else:
            print("Someone tried to login and failed")
            print("Username : {} and password {}".format(username, password))
            return HttpResponse("invalid login details suppliec")
    
    else:
        return render(request, 'first_app/login.html', {})

templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title> </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li> <a class="navbar-brand" href="{% url 'first_app:index' %}"> DJANGO</a></li>
                    <li> <a class="navbar-brand" href="{% url 'admin:index' %}"> Admin</a></li>
                    <li> <a class="navbar-brand" href="{% url 'first_app:register' %}"> Register</a></li>

                    {% if user.is_authenticated %}
                        <li> <a class="navbar-link" href="{% url 'first_app:user_logout' %}"> Logout</a></li>
                    {% else %}
                    <li> <a class="navbar-brand" href="{% url 'first_app:user_login' %}"> Login </a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inheritated -->
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/first_app/form_page.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title> Form </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <h1> Sign Up</h1>
            
        <div class="container">
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit", class="btn btn-primary" value="Submit">
            </form>
    
        </div>
    </body>
</html>

templates/first_app/home.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title> Home </title>
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
    </head>
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1> Home Page</h1>
            </div>
            
            <img src="{% static 'images/djangotest.jpg' %}" alt="My image">
           
            <div class="djangotwo">
                {% if access_records %}
                <table class="landingpage">
                    <thead>
                        <th> Site Name</th>
                        <th> Date Accessed </th>
                    </thead>
                    {% for acc in access_records %}
                    <tr>
                        <td> {{ acc.name }}</td>
                        <td> {{ acc.date }}</td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                    <p> NO ACCESS RECORDS</p>
                {% endif %}
            </div>
        </div>

        <a href="{% url 'first_app:signup_name' %}"> Go to sign up page </a>

    </body>
</html>

templates/first_app/index.html
{% extends "first_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1> Django Level Five </h1>
    </div>
{% endblock %}

templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotoron">
    <h1> Please Login </h1>
    <form action="{% url 'first_app:user_login' %}" method="POST"> 
        {% csrf_token %}
        <label for="username"> Username: </label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password"> Password: </label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

templates/first_app/registration.html
{% extends "first_app/base.html" %}
{% load static %}

{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1> Thank you for registering </h1>
        {% else %}
            <h1> Register here </h1>
            <h3> Fill out the form </h3>

            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit", class="btn btn-primary" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/first_app/signup_page.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title> Form </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <h1> Sign Up</h1>

            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit", class="btn btn-primary" value="SignUp">
            </form>
    
        </div>
    </body>
</html>